### ISSUE TITLE
Linux Mint OS

### ISSUE THREAD

**Issue by syedasara-angelium** [joeVenner/control-3d-character-using-python#4]
Can I do this on Linux Mint OS?
I installed Blender using Software Manager in Linux Mint  (which is 2.91.0)
where do I install the 2 libraries?

**Comment by joeVenner** [comment]
Hi Syedasara,

Yes it will work on Linux,
For the libraries, you can just install them using `pip` command, the same as in windows

If you have any other questions feel free to let me know!

**Comment by syedasara-angelium** [comment]
Thanks alot
